### ISSUE TITLE
Wrong channel detail when scrolling

### ISSUE THREAD

**Issue by gehlm** [edouardparis/lntop#11]
- Run lntop with many open channels.
- Resize terminal window so that channel list exceeds window height
- Scroll channel list to bottom
- Press Enter to get detail

Program displays data for wrong channel. Can be fixed by scrolling up to the first channel in the list.

**Comment by edouardparis** [comment]
Thank you ! I did reproduce the bug and applied a fix, please tell me if everything is ok for you and send me a tip page for sats

**Comment by gehlm** [comment]
Fixed, thanks.

**Comment by edouardparis** [comment]
Oups, redimension change the index, I need to fix it again sorry

**Comment by edouardparis** [comment]
should be good in v0.0.3
