### ISSUE TITLE
Error in log

### ISSUE THREAD

**Issue by C-Otto** [edouardparis/lntop#13]
{"level":"error","ts":1556304206.854988,"caller":"models/models.go:70","msg":"refreshChannels: cannot find Node","logger":"models","pubkey":"03a9d79bcfab7feb0f24c3cd61a57f0f00de2225b6d31bce0bc4564efa3b1b5aaf","stacktrace":"github.com/edouardparis/lntop/ui/models.(*Models).RefreshChannels\n\t/home/cotto/go/src/github.com/edouardparis/lntop/ui/models/models.go:70\ngithub.com/edouardparis/lntop/ui.(*controller).SetModels\n\t/home/cotto/go/src/github.com/edouardparis/lntop/ui/controller.go:74\ngithub.com/edouardparis/lntop/ui.Run\n\t/home/cotto/go/src/github.com/edouardparis/lntop/ui/ui.go:21\ngithub.com/edouardparis/lntop/cli.run.func1\n\t/home/cotto/go/src/github.com/edouardparis/lntop/cli/cli.go:67"}

**Comment by C-Otto** [comment]
That node is in waiting_close state

**Comment by edouardparis** [comment]
Thank you ! Sadly lnd does not keep node information when channel is closing, the daemon return an error when asked to search node with given pubkey. I changed the log label for debug.
