### ISSUE TITLE
Question: plans for ARM binaries?

### ISSUE THREAD

**Issue by Stadicus** [edouardparis/lntop#16]
Hej Edouard, thanks for this nifty tool! Do you plan to provide binary releases for the ARM platform, eg. ARMv7 for modern Raspberry Pis? 

I think these are a primary target group  for a tool like this, and I'd like to include it in my RaspiBolt guide. Compiling from scratch, however, is a bit of a stretch for a Beginner's guide.

**Comment by edouardparis** [comment]
Hello ! Thank you for your kind words, i really like your guide. I added arm build configuration to the release tool `goreleaser` and updated the latest release assets. I have no experience with raspberry, but I guess I should be more vigilant about memory usage now.
 Please, keep me informed about any problems (until i join the fun of the raspibolt community).

**Comment by Stadicus** [comment]
Thanks, I'll test is asap.

**Comment by edouardparis** [comment]
I saw that lntop was added to you guide: https://stadicus.github.io/RaspiBolt/raspibolt_74_lntop.html
I am closing the issue and promise to not forget to create arm binary to each release. 
Thank you for your work and for testing the software.
