### ISSUE TITLE
lnd-v0.11.99  mainnet [syncing] after new block

### ISSUE THREAD

**Issue by githorray** [edouardparis/lntop#20]
When lntop starts it shows status as **[synced]** in green, but since the lnd 0.11.99 tag, after a new block, lntop will then show **[syncing]** in orange and never return back to **[synced]** in green even though LND is synced.

```
$ lnd --version
lnd version 0.11.99-beta commit=v0.11.0-beta-90-g8668248d96a0531075513c8c32a5d3f63e325483

$ lntop --version
lntop version v0.1.0
```

**Comment by edouardparis** [comment]
I did not update lntop for a long time and lnd has a lot of new stuff. I will work on it when I have time.
Thank you for reporting the issue :pray:

**Comment by githorray** [comment]
Thank you for a great tool.

**Comment by githorray** [comment]
Maybe related to this.
https://github.com/lightningnetwork/lnd/pull/5328

**Comment by githorray** [comment]
fixed in LND
https://github.com/lightningnetwork/lnd/pull/5328
