### ISSUE TITLE
Routing view breaks on FEE_INSUFFICIENT events

### ISSUE THREAD

**Issue by rkfg** [edouardparis/lntop#25]
The new routing view by @mmilata is great, however it becomes unusable on events with details like `FEE_INSUFFICIENT NO_DETAIL FeeInsufficient(htlc_amt==7000 mSAT, update=(lnwire.ChannelUpdate) {` (a structure dump follows). It looks like this: 
![2021-06-16_02-01-00](https://user-images.githubusercontent.com/184066/122134462-4d4fb000-ce47-11eb-973b-95ef45d4196f.png)

**Comment by mmilata** [comment]
Yeah that looks unusable:) The solution is probably to discard everything after first linebreak. Do you know how to easily reproduce this condition, for testing?

**Comment by edouardparis** [comment]
Thank you for reporting the issue. It is possible to edit your config toml and do not include the detail column:
```
[views.routing]
columns = [
	"DIR",            # event type:  send, receive, forward
	"STATUS",         # one of: active, settled, failed, linkfail
	"IN_CHANNEL",     # channel id of the incomming channel
	"IN_ALIAS",       # incoming channel node alias
	# "IN_HTLC",      # htlc id on incoming channel
	# "IN_TIMELOCK",  # incoming timelock height
	"OUT_CHANNEL",    # channel id of the outgoing channel
	"OUT_ALIAS",      # outgoing channel node alias
	# "OUT_HTLC",     # htlc id on outgoing channel
	# "OUT_TIMELOCK", # outgoing timelock height
	"AMOUNT",         # routed amount
	"FEE",            # routing fee
	"LAST UPDATE"    # last update
	# "DETAIL"  <--------------------------comment this line
]
```
Maybe the solution would be to not print the detail in the list view, but only when an event is selected.

**Comment by rkfg** [comment]
> Yeah that looks unusable:) The solution is probably to discard everything after first linebreak. Do you know how to easily reproduce this condition, for testing?

I don't know if it's possible to reliably reproduce this. Insufficient fee error happens when some channel's fee has been increased but your node isn't yet aware of this and uses the last known (lower) fee. So it's sort of a race condition on the network scale and these things are hard to reproduce usually. I guess using only the first line is a good enough solution if you parse the log.

> Thank you for reporting the issue. It is possible to edit your config toml and do not include the detail column:

Also a good workaround, thanks!

**Comment by mmilata** [comment]
Heh, saw this issue for the first time today, also happens when someone tries to forward less than the minimal mSAT amount.

I opened #26 with simple fix that only keeps the first line. Showing the full detail on enter would be nice to have but not something i can do right now.

**Comment by rkfg** [comment]
Since #26 is merged this can be closed. Thanks!
