### ISSUE TITLE
Can't see routing view on my node

### ISSUE THREAD

**Issue by grunch** [edouardparis/lntop#40]
Hey everyone, I can't find a way to see the routing view, I already have the `[views.routing]` section on the `~/.lntop/config.toml` file and still I don't see this option when I press F2, any ideas?

![Captura de pantalla de 2021-08-31 16-12-45](https://user-images.githubusercontent.com/228364/131562665-5cc7a0eb-58fe-4579-975b-d7ef2e1e8431.png)

**Comment by edouardparis** [comment]
If you installed lntop with `go install ...@latest`, you have the last version but not the last commit on master.
Routing view is not part of version 0.1, I need to tag a new version.
For the moment you can I think, clone the repository and run 'go install ./...'

**Comment by grunch** [comment]
compiled and now is working, thanks
