### ISSUE TITLE
Question: binaries releases planned?

### ISSUE THREAD

**Issue by Stadicus** [edouardparis/lntop#49]
Hi Edouard, remember https://github.com/edouardparis/lntop/issues/16? :)

We're currently updating the RaspiBolt v3 bonus guides. The guide on lntop uses the binaries, and is still on version 0.1.0. I noticed that you recently released lntop v0.2.0, but there are no binary files.

Current pull request: https://github.com/raspibolt/raspibolt/pull/811

Do you plan to provide binary releases? For the RaspiBolt v3 guide, ARM64 would be especially interesting.

If not: no problem. Then we'd need to rewrite the guide for users to compile the tool themselves. Not as easy, of course, but doable.

**Comment by edouardparis** [comment]
Hi Stadicus, yes I am sorry I did not provide the binary.
I compiled one on my computer and attached it to the [v0.2.0](https://github.com/edouardparis/lntop/releases/tag/v0.2.0).
RELEASE.md in the tar.gz should provide enough information if someone want to reproduce the build.

I got inspired by the https://raspibolt.org/lnd.html#installation section and provided a signature of the tar.gz checksum.

```
curl https://edouard.paris/key.asc | gpg --import
gpg --verify checksums-lntop-v0.2.0.txt.sig checksums-lntop-v0.2.0.txt 
sha256sum --check checksums-lntop-v0.2.0.txt
```

**Comment by Stadicus** [comment]
That's what I call great service, thanks! :)

**Comment by Stadicus** [comment]
FYI, the file you uploaded is a simple tar archive, and not gzipped. I think the correct file suffix would be just `.tar`. But works anyway, if you know how to handle it.

```sh
$ tar -xvzf lntop-v0.2.0-Linux-arm64.tar.gz 

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

$ file lntop-v0.2.0-Linux-arm64.tar.gz 
lntop-v0.2.0-Linux-arm64.tar.gz: POSIX tar archive (GNU)

$ tar -xvf lntop-v0.2.0-Linux-arm64.tar.gz 
release/
release/RELEASE.md
release/LICENSE
release/lntop
 ```
