### ISSUE TITLE
Add column `age` to channel view

### ISSUE THREAD

**Issue by hieblmi** [edouardparis/lntop#82]
A channel age column in the channels view would come in handy - `age ~ (current block height - short chan id height)*144`

**Comment by rkfg** [comment]
Nice idea! I like Amboss viewer the most and I prefer their features to be available locally, like disabled channel count (implemented in the PR) and channel age. I think it could be abbreviated too because days are harder to comprehend. Something like `1y2m10d` looks short and understandable to me.

**Comment by rkfg** [comment]
Apparently there's no API to query specific tx/block data in lnd so the age would be approximate as you've described. It's possible to subscribe to new txs and blocks but not to retrieve the historic data. It can only be done wtih Bitcoin RPC and that's another dependency and a bunch of config options just for one minor feature, probably not worth it.

Interestingly enough, Amboss does the same calculation and it's not precise as well. I chose my [oldest channel](https://amboss.space/edge/764004450833465345), Amboss says it's 1 year 44 days old. However, the opening tx is dated 2021-08-09 which was 1 year 33 days ago. Calculating `(753793-694858)*10min` gives 1 year 44 days exactly. Clearly, this simple math is way faster for this purpose than digging the blockchain for every channel, and the error isn't that big on a scale (≈10 days every year).

**Comment by hieblmi** [comment]
Nice investigation, yes this approximation seems to serve the purpose well enough. We might even want to express the vagueness of the age in the via with something like `~1y2m10d`. I'd be happy to pick this up in my next free slot if you don't mind.

**Comment by rkfg** [comment]
Oops, I've already implemented it... See if it looks fine, I decided to show hours only for channels younger than 1 year.
![2022-09-12_17-36-18](https://user-images.githubusercontent.com/184066/189682464-7114b22a-2dd8-484d-bed1-ba5fb867e860.png)
![2022-09-12_17-36-28](https://user-images.githubusercontent.com/184066/189682484-3819ea8b-6a06-4737-bfe4-e1350d0acaea.png)

**Comment by hieblmi** [comment]
Very speedy :D. Thanks for the feature!

**Comment by rkfg** [comment]
Most of the time if channels aren't ordered by age you can quickly determine how old they are from:
- value length (short values mean less than 1 month, very short — less than 1 day)
- first number for equally long values (month/day/hour) which is usually the number of months. For very old channels that's the number of years and most probably there aren't many such channels on your node so if this number is 01 or 02 look at the letter after it.
