### ISSUE TITLE
feature-request: Show `blocks_til_maturity` in channel view for force closed channels.

### ISSUE THREAD

**Issue by hieblmi** [edouardparis/lntop#91]
It would be nice to see in the channel view when a force-closure matures.

**Comment by hieblmi** [comment]
Closing this issue since it has been merged in the linked MR.

**Comment by rkfg** [comment]
I don't want to open a new issue just for this but there's a minor bug in the current implementation: right after the channel was force closed the maturity number is zero and it doesn't change unless I restart lntop. Probably need to use or add some event subscription?
